name: release
on:
  workflow_dispatch:
jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - name: Setup asdf
        uses: asdf-vm/actions/setup@v3
        # 2回目以降エラーが出るが問題ない
        continue-on-error: true
      - name: asdf install
        uses: asdf-vm/actions/install@v3
      - name: Install dependencies
        run: yarn install --immutable
      - name: generate and type-check
        run: |
          yarn generate
          yarn type-check
      - name: prepare release
        run: |
          sed .gitignore -i -e s/dist//g
          VERSION=$(cat package.json | jq -r .version)
          git config user.name "actions-user"
          git config user.email "action@github.com"
          git add .gitignore
          git add dist
          git commit -m "release ${VERSION}"
          git tag -a "v${VERSION}" -m "release ${VERSION}"
          git push origin --tags
